### ISSUE TITLE
SQL Exception

### ISSUE THREAD

**Issue by getdatakick** [eschiendorfer/genzo_krona#9]
Looks like customer id was not resolved correctly

#### Error Message:
```
ThirtyBeesDatabaseException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') AND (id_order = 5782) LIMIT 1' at line 3
```

#### Location:
`modules/genzo_krona/classes/PlayerHistory.php line 121`

https://github.com/eschiendorfer/genzo_krona/blob/a09187afa225df3afd79dd6ab4c3d5c85d0ba623/classes/PlayerHistory.php#L115-L122

#### SQL
```sql
SELECT id_history
FROM `ps_genzo_krona_player_history`
WHERE (id_customer = ) AND (id_order = 5782) LIMIT 1
```

#### Stacktrace
```
#5  modules/genzo_krona/classes/PlayerHistory.php(121): DbCore->getValue(DbQuery#1)
#6  modules/genzo_krona/genzo_krona.php(1117): KronaModule\PlayerHistory::getIdHistoryByIdOrder(null, 5782)
#7  modules/genzo_krona/genzo_krona.php(1053): Genzo_Krona->processOrder(Order#1)
#8  classes/Hook.php(769): Genzo_Krona->hookActionOrderStatusPostUpdate(array(6))
#9  classes/Hook.php(471): HookCore::coreCallHook(Genzo_Krona#1, "hookactionOrderStatusPostUpdate", array(6))
#10 classes/Hook.php(288): HookCore::execWithoutCache("actionOrderStatusPostUpdate", array(6), null, false, true, false, "1")
#11 classes/order/OrderHistory.php(373): HookCore::exec("actionOrderStatusPostUpdate", array(3), null, false, true, false, "1")
#12 controllers/admin/AdminOrdersController.php(673): OrderHistoryCore->changeIdOrderState(4, Order#1, false)
#13 classes/controller/Controller.php(204): AdminOrdersControllerCore->postProcess()
#14 classes/Dispatcher.php(861): ControllerCore->run()
#15 admin429zfhthp/index.php(58): DispatcherCore->dispatch()
```

**Comment by eschiendorfer** [comment]
Thanks for the report! I will have a look at it. I have my internal and official branch. Lately I was only fixing little stuff on internal as I got no feedback on this module. But I will change that as I have learnt to work with multiple branches :)
